# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02240a1df1c08c7ae2c87c6fc1ec48c65e5b28e1a8efc90ffef16812213dea3f244f826bbf3b62ead056f4a1b3f6a42f13fbd09871afe104eede56dc8bccce4d

test:
  secret_key_base: c36952078b145136dd9038ea98051b98e68a68a498e0f25af57af30d8b4df07ee1a5647826c5f08db5e73bb78abafc43fda1529374337a1af7a0a17dbc55b487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
